### ISSUE TITLE
[Feature Request] Jpg and other file type support

### ISSUE THREAD

**Issue by PeterHindes** [wrmndfzzy/Atomize#11]
Its inconvenient to only be able to chose pngs as a source.

**Comment by frap129** [comment]
Atomize is a front end for the `pngquant` image compression tool. It doesn't accept other file types. I'v experimented with converting jpg to png before quantizing, but that results in a larger file than the original jpg.

**Comment by PeterHindes** [comment]
Since I'm not especially interested in size, I would appreciate it if, in the event that you still have any of that code arround if you could show me it. Thanks for considering.
